### ISSUE TITLE
Add Agilent MSO6104A support via SCPI

### ISSUE THREAD

**Issue by clh27** [azonenberg/scopehal#74] opened 2019-06-05 08:14 UTC

**Comment by miek** [comment] 2019-09-27 14:48
I've got the beginnings of a driver working for the DSO5014A here: https://github.com/miek/scopehal/tree/agilent
It will probably just work on the 6000 & 7000 series if you want to try it out.

**Comment by miek** [comment] 2020-06-09 17:09
Duplicate of #14 - the MSO6104A should work just fine with the Agilent driver I'm developing on an MSO6034A

**Closed by miek** 2020-06-09 17:09 UTC
Labels: driver
